/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.*;
import BLL.*;
import java.sql.ResultSet;
public class ThongTinNhanVien extends javax.swing.JFrame {

    public static String sql="select ROW_NUMBER() OVER (ORDER BY HOTENNV) STT,MANV as [Mã NV],HOTENNV as [Họ và tên],DIACHI as [Địa chỉ],THUONGTRU as [Thường trú],SODIENTHOAI as [SĐT],NGAYSINH as [Ngày sinh],NOISINH as [Nơi sinh],case when GIOITINH=1 then N'Nam' else N'Nữ' end as [Giới tính],CMND,QUEQUAN as [Quê quán],DANTOC as [Dân tộc],GHICHU as [Ghi chú],TENPB as [Tên PB],TENCV as [Tên CV],MATKHAU as [Mật khẩu] from dbo.NHANVIEN, dbo.CHUCVU, dbo.PHONGBAN where dbo.NHANVIEN.MACV=dbo.CHUCVU.MACV and dbo.NHANVIEN.MAPB=dbo.PHONGBAN.MAPB";
    public ThongTinNhanVien() {
        initComponents();
        UpdataTable.loadData(sql, tblnhanvien);
        this.lblTB.setText("Danh sách có "+this.tblnhanvien.getRowCount()+" nhân viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhanvien = new javax.swing.JTable();
        txttk = new javax.swing.JTextField();
        btbtim = new javax.swing.JButton();
        lblTB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách nhân viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");

        tblnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblnhanvien);

        btbtim.setText("Tìm kiếm");
        btbtim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbtimActionPerformed(evt);
            }
        });

        lblTB.setForeground(new java.awt.Color(255, 0, 51));
        lblTB.setText("jLabel2");

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbtim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTB)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel1)
                .addGap(0, 479, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btbtim)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTB)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbtimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbtimActionPerformed
        if(this.txttk.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Bạn chưa nhập từ khóa cần tìm", "Thông báo",1);
        else
        {
            String sql1="select ROW_NUMBER() OVER (ORDER BY HOTENNV) STT,MANV as [Mã NV],HOTENNV as [Họ và tên],DIACHI as [Địa chỉ],THUONGTRU as [Thường trú],SODIENTHOAI as [SĐT],NGAYSINH as [Ngày sinh],NOISINH as [Nơi sinh],case when GIOITINH=1 then N'Nam' else N'Nữ' end as [Giới tính],CMND,QUEQUAN as [Quê quán],DANTOC as [Dân tộc],GHICHU as [Ghi chú],TENPB as [Tên PB],TENCV as [Tên CV],MATKHAU as [Mật khẩu] from dbo.NHANVIEN, dbo.CHUCVU, dbo.PHONGBAN where MANV like'%"+this.txttk.getText()+"%' OR HOTENNV like'%"+this.txttk.getText()+"%' and dbo.NHANVIEN.MACV=dbo.CHUCVU.MACV and dbo.NHANVIEN.MAPB=dbo.PHONGBAN.MAPB";
            UpdataTable.loadData(sql1, tblnhanvien);
            this.lblTB.setText("Danh sách có "+this.tblnhanvien.getRowCount()+" nhân viên");
        }
    }//GEN-LAST:event_btbtimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbtim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTB;
    private javax.swing.JTable tblnhanvien;
    private javax.swing.JTextField txttk;
    // End of variables declaration//GEN-END:variables
}
