/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.*;
import BLL.*;
import java.sql.ResultSet;

public class TK_LuongNhanVien extends javax.swing.JFrame {

    public static String sql="select ROW_NUMBER() OVER (ORDER BY HOTENNV) STT, MALUONG [Mã lương],HOTENNV [Tên NV],THANG [Tháng],LUONGTAMUNG [Lương tạm ứng],NGAYLAMVIEC [Ngày làm việc],TIENLUONG [Tiền lương],BHXH,BHYT,TIENTHUONG [Tiền thưởng], SUM(TIENLUONG*NGAYLAMVIEC/26+TIENTHUONG+(-BHXH)+(-BHYT)+(-LUONGTAMUNG)) as [Tổng lương] from dbo.LUONG, dbo.NHANVIEN, dbo.THUONG where dbo.LUONG.MANV=dbo.NHANVIEN.MANV and dbo.NHANVIEN.MANV=dbo.THUONG.MANV GROUP BY MALUONG,HOTENNV,THANG,LUONGTAMUNG,NGAYLAMVIEC,BHXH,BHYT,TIENLUONG,TIENTHUONG";
    public TK_LuongNhanVien() {
        initComponents();
        UpdataTable.loadData(sql, tblluong);
        this.lblTB.setText("Danh sách có "+this.tblluong.getRowCount()+" nhân viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblluong = new javax.swing.JTable();
        txttk = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        lblTB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê lương");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("THÔNG TIN LƯƠNG");

        tblluong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblluong);

        btntim.setText("Tìm kiếm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });

        lblTB.setForeground(new java.awt.Color(255, 51, 51));
        lblTB.setText("jLabel2");

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(453, 453, 453)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTB)))
                        .addGap(0, 453, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntim)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        if(this.txttk.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Bạn chưa nhập từ khóa cần tìm", "Thông báo",1);
        else
        {
            String sql1="select ROW_NUMBER() OVER (ORDER BY HOTENNV) STT, MALUONG [Mã lương],HOTENNV [Tên NV],THANG [Tháng],LUONGTAMUNG [Lương tạm ứng],NGAYLAMVIEC [Ngày làm việc],TIENLUONG [Tiền lương],BHXH,BHYT,TIENTHUONG [Tiền thưởng], SUM(TIENLUONG*NGAYLAMVIEC/26+TIENTHUONG+(-BHXH)+(-BHYT)+(-LUONGTAMUNG)) as [Tổng lương] from dbo.LUONG, dbo.NHANVIEN, dbo.THUONG where dbo.LUONG.MANV=dbo.NHANVIEN.MANV and dbo.NHANVIEN.MANV=dbo.THUONG.MANV and HOTENNV like'%"+this.txttk.getText()+"%' OR MALUONG like'%"+this.txttk.getText()+"%' GROUP BY MALUONG,HOTENNV,THANG,LUONGTAMUNG,NGAYLAMVIEC,BHXH,BHYT,TIENLUONG,TIENTHUONG";
            UpdataTable.loadData(sql1, tblluong);
            this.lblTB.setText("Danh sách có "+this.tblluong.getRowCount()+" nhân viên");
        }
    }//GEN-LAST:event_btntimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TK_LuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TK_LuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TK_LuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TK_LuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TK_LuongNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTB;
    private javax.swing.JTable tblluong;
    private javax.swing.JTextField txttk;
    // End of variables declaration//GEN-END:variables
}
